### ISSUE TITLE
Enable smart contract addresses in contacts store

### ISSUE THREAD

**Issue by ElliotFriend** [stellar/basic-payment-app#19]
Right now, [we're checking](https://github.com/stellar/basic-payment-app/blob/ce7defb7a4d3d3d63e4dc74435616180f2040124/src/lib/stores/contactsStore.js#L44-L57) that an entered contact has a valid `G...` address. We should update this `add` function so it can check for and allow contacts with smart contract `C...` addresses.

**Comment by ShantelPeters** [comment]
Hi @ElliotFriend please i will like to work on this issue when the OD hack begins

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps, ETHGlobal  and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the DojoCoding community.
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.


### How I plan on tackling this issue
To address the requirements of the issue, I will:

1. Update the add function in the contacts store to accept and validate smart contract addresses that start with "C...".
2. Modify the existing validation logic to check for both standard G... addresses and the new C... addresses.
3. Ensure that the input format for smart contract addresses adheres to any relevant standards or patterns.
4. Test the updated add function to verify that it correctly accepts valid smart contract addresses and rejects invalid ones.

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I am a SC developer

### How I plan on tackling this issue
I can work on this

**Comment by aji70** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
i'm a solidity and cairo smart contract  developer with over 2 years experience and believe i have the skill set for the task and i am also very good with smart contract testing

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
GM, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, JavaScript and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
Hi @ElliotFriend, I would approach this issue like this:

- We can add an extra check in the add function to check for both valid Ed25519 public keys and Smart Contract addresses. Here's the relevant code for the `C...`address checking: 
```
const isValidContractAddress = StrKey.isValidContract(contact.address);
```

- The if condition has to be changed now to be `isValidEd25519PublicKey || isValidContractAddress` so that either of the two being true will successfully execute the function.

## Tasks:
- [ ] Implement the `C...` contract checking logic

## ETA: 5 Hours

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
hello i am Shantel, a blockchain developer .and technical writer ,i have a high capacity to tackle issues. i hope this issue is assigned to me , i am avalaible to work 

### How I plan on tackling this issue
i will approach the problem with the following:
1. Update Validation Logic: Modify the existing validation function for contact addresses to include checks for both G... and C... addresses.
2. Identify Address Types: Ensure the function can differentiate between a regular G... address and a smart contract C... address, validating the format appropriately.
3. Adjust Add Function: Update the `add` function to allow the entry of C... addresses, ensuring it calls the modified validation logic.
4. Test Functionality: Test the updated function to ensure it correctly accepts both types of addresses without errors.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I  am  a  blockchain developer with experience in smart contract integration, 

### How I plan on tackling this issue
To tackle the issue, I would:

 Examine the existing address validation logic for G... addresses.

 Determine the criteria for validating C... addresses, ensuring they conform to the expected format.

 Modify the add function to include a check for both G... and C... addresses, allowing valid C... addresses to be accepted.

Implement tests to ensure both types of addresses are validated correctly without breaking existing functionality.

 Update any relevant documentation to reflect the changes in address validation.

**Comment by SoarinSkySagar** [comment]
Hi @ElliotFriend, sorry for the late follow up.
I have understood what I need to do for this issue, but I have a few questions:
- Since there's no function to check for `C...` addresses in the stellar-base package, I would have to create a custom function for it. From what I can see in the `isValidEd25519PublicKey` definition in the `node_modules`, these are the criteria for the `C...` address:
  - `length === 56`
  - `address[0] === "C"`
- Should I write the custom function in `src/lib/utils/devHelpers.js` or somewhere else?

PS.: Please accept my friend request on Discord (I am kxizen on Discord) so that we can have faster communications :)

**Comment by SoarinSkySagar** [comment]
Hi @ElliotFriend, created PR #31 to close this issue; please review
