### ISSUE TITLE
Update all dependencies

### ISSUE THREAD

**Issue by ElliotFriend** [stellar/basic-payment-app#2]
We do have dependabot configured on this repo, as of #5. However, many packages are probably due for a major version upgrade. Let's do as many of those as possible.

Especially important is the `@stellar/stellar-sdk` dependency (which we should move to, instead of the currently used `stellar-sdk` package). At the moment, the current version is [v12.3.0](https://github.com/stellar/js-stellar-sdk/releases/tag/v12.3.0)

_Edit:_ Dependabot has create #11, but it may result in some breaking changes that need some human intervention

_Another Edit:_ We should also migrate to node `v20` while we're at it. The [`update-protocol-20` branch](https://github.com/stellar/basic-payment-app/tree/update-protocol-20) has some work started to this end, though I'm sure it's incomplete atm.

**Comment by Joy-Adah** [comment]
Hi @ElliotFriend I would love to work on this. Can I be assigned?

**Comment by sanieni6** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hi! My name is Luis Sanchez, and I’m a Frontend Developer with 3 years of experience, specializing in TypeScript and React. I'm gonna be glad to contribute


### How I plan on tackling this issue
well, First, I’ll review the current state of the dependencies, particularly focusing on the @stellar/stellar-sdk and the node v20 migration. I’ll start by updating the @stellar/stellar-sdk package, replacing the older stellar-sdk version. I will address any breaking changes by reviewing the changelog and updating the affected code accordingly. After that, I’ll proceed with the Node v20 migration,  Finally, I’ll document the changes and update any relevant documentation.

**Comment by Joy-Adah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hi. My name is Joy and I am a web3 developer and contributor. 

### How I plan on tackling this issue
I plan to update all dependencies, including the Stellar SDK and Node, to their latest versions. My plan is to carefully go through the existing dependencies, ensure compatibility with the latest versions, and test the changes thoroughly to avoid breaking existing functions.

**Comment by diegoTech14** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hello @ElliotFriend,

I'm a software engineer from Costa Rica with over 1 year of experience and a member of Dojo Coding. I have worked with backend technologies such as Node.js, PhP, Java, C#, Cairo. I'd love the opportunity to help with this issue and contribute to your project.

### How I plan on tackling this issue
As I'm new to the project, my first step will be to thoroughly understand the codebase and get the necessary context. This will involve familiarizing myself with the architecture, dependencies, and existing documentation, allowing me to make informed decisions moving forward.

For this issue I will:

`1.` Start to identify all dependencies that need to update
`2.` Look for the stable and most recent version and update
`3.` Generate any documentation if it is needed

Looking forward to hearing from you!

Best regards.

**Comment by gregemax** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I have experience in JavaScript and package management, with a strong focus on upgrading dependencies and ensuring compatibility. I’ve worked on similar projects where I migrated packages and handled breaking changes, which will help me effectively manage the upgrade from stellar-sdk to @stellar/stellar-sdk and transition to Node v20.


### How I plan on tackling this issue
I would start by reviewing the Dependabot PR (#11) for potential breaking changes, then upgrade the packages incrementally, focusing on transitioning from stellar-sdk to @stellar/stellar-sdk. I’d also migrate the project to Node v20, addressing any issues that arise during testing to ensure compatibility. Finally, I’d document the changes for future reference.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will approach this issue in the following manner: 

  

1. I will review the current `package.json` and identify all outdated dependencies. 

2. I will update `@stellar/stellar-sdk` to the latest version (v12.3.0 or newer): 

   a. Replace `stellar-sdk` with `@stellar/stellar-sdk` 

   b. Update import statements throughout the project 

   c. Address any breaking changes in the SDK 

3. I will systematically update other dependencies, prioritizing security updates: 

   a. Update each package individually 

   b. Test the application after each update 

   c. Address any breaking changes or deprecations 

4. I will upgrade the project to use Node.js v20: 

   a. Update the `engines` field in `package.json` 

   b. Modify any Node.js-specific code to be compatible with v20 

   c. Update CI/CD configurations to use Node.js v20 

5. I will thoroughly test the application after all updates to ensure functionality. 

6. I will update the project documentation to reflect the new dependency versions and Node.js requirement.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hello @ElliotFriend  I am Joseph I am a Softwaremdeveloper and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. 

### How I plan on tackling this issue
I will have to update the dependecies to match the description. And I will ensure that they are updated by tomorrow if assigned the PR

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
hello i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor


### How I plan on tackling this issue
Check Current Dependencies: Review package.json for packages due for major version upgrades.

Update @stellar/stellar-sdk: Replace stellar-sdk with @stellar/stellar-sdk and update to the latest version, addressing any breaking changes.

Run Dependabot: Review the Dependabot pull request (#11) for updates and breaking change notifications.

Test for Breaking Changes: Run tests and adjust code as needed to handle breaking changes from the updates.

Migrate to Node v20: Update the project to Node v20, referencing the update-protocol-20 branch for guidance.

Final Testing: Run the application and tests to ensure everything functions correctly after updates.

Commit Changes: Commit updates with a clear message about the dependency and Node version changes.

Documentation: Optionally, update the README to reflect the changes made.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I have experience on full stack development building an EVM explorer and indexer: https://github.com/walnuthq/op-scan


### How I plan on tackling this issue
I will continue the work started on the update-protocol-20 branch and make sure every dependency is up to date, following the migration paths described in each package CHANGELOG.
