### ISSUE TITLE
Testnet accounts should be checked for funding when signing in

### ISSUE THREAD

**Issue by ElliotFriend** [stellar/basic-payment-app#7]
Following a Testnet reset, when logging into an account that was set up before the reset, the login will fail with a 404 error, since the account is no longer live on the Testnet.

The [`fetchAccount` function](https://github.com/stellar/basic-payment-app/blob/59e4877d04106cf237a59c0abc6b86cfcec4261f/src/lib/stellar/horizonQueries.js#L33) in `/src/lib/stellar/horizonQueries.js` should be modified to go ahead and fund the account in the event it finds a 404 response from the Horizon server.

**Comment by od-hunter** [comment]
Hi @ElliotFriend , please can I be assigned this once od hack starts?

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
1. **Modify the `fetchAccount` Function to Handle 404 Errors:**
   - I will modify the `fetchAccount` function to check if the 404 error occurs when querying the Horizon server. Instead of throwing an error immediately, I will trigger a call to the `fundWithFriendbot` function to fund the account in case of a 404 error (i.e., the account no longer exists on the Testnet after a reset).
   
2. **Add Logic to Fund Accounts Automatically:**
   - After detecting a 404 error, I will attempt to fund the account using the `fundWithFriendbot` utility. Once funded, I will retry fetching the account details to confirm the account's existence and return the account data.
   
3. **Update `fetchAccount` Function:**
   - Here’s an updated version of the `fetchAccount` function to include the automatic funding step:

   ```javascript
   export async function fetchAccount(publicKey) {
       if (StrKey.isValidEd25519PublicKey(publicKey)) {
           try {
               let account = await server.accounts().accountId(publicKey).call()
               return account
           } catch (err) {
               if (err.response?.status === 404) {
                   console.log(`Account ${publicKey} not found on the network. Funding with Friendbot...`)
                   
                   // Attempt to fund the account
                   try {
                       await fundWithFriendbot(publicKey)
                       console.log(`Account ${publicKey} successfully funded!`)
                       
                       // Retry fetching the account
                       let account = await server.accounts().accountId(publicKey).call()
                       return account
                   } catch (fundError) {
                       throw error(500, { message: `Failed to fund account ${publicKey}: ${fundError.message}` })
                   }
               } else {
                   throw error(err.response?.status ?? 400, {
                       message: `${err.response?.title} - ${err.response?.detail}`,
                   })
               }
           }
       } else {
           throw error(400, { message: 'invalid public key' })
       }
   }
   ```

4. **Test the Changes:**
   - After implementing the changes, I will thoroughly test the login process with accounts that are unfunded, previously funded but reset, and newly created, to ensure that the funding mechanism works as expected.

ETA - 3 days

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I'm a Solidity developer skilled in building decentralized applications and integrating 
 multi-token support . My experience can help address issues like  automatically funding accounts on Testnet after resets, ensuring a seamless user experience.

### How I plan on tackling this issue
To approach this issue ----- >
1.  Check for 404 error in the `fetchAccount` function when logging in.
2.  f 404 occurs, automatically fund the account on the Testnet.
3.  Modify `/src/lib/stellar/horizonQueries.js` to handle the response and trigger the funding process when needed.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this repo and I'd love to be given the opportunity. I have experience in html, css, react, JavaScript,TypeScript and solidity, python and Cairo.

### How I plan on tackling this issue
To solve this issue, I’d take the following steps:
1.⁠ ⁠First of all, I’ll have to understand the current logic of the fetchAccount function.
2.⁠ ⁠⁠I’ll update the function to check for a 404 response when fetching the account.
3.  If a 404 error is detected, I’ll initiate the funding process for the account using a funding function.
4.⁠ ⁠I’ll modify fetchAccount to handle 404s and call the funding function when needed.
5.⁠ ⁠⁠I’ll verify that the function behaves correctly by funding accounts that are no longer live and handling existing accounts properly.
6.⁠ ⁠⁠Lastly, I’ll provide documentation for the modifications made to the function and the new error handling logic.

Please assign me. I'm ready to work.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will approach this issue in the following manner: 

  

1. I will modify the `fetchAccount` function in `/src/lib/stellar/horizonQueries.js`: 

   a. Add error handling for 404 responses from the Horizon server 

   b. Implement logic to fund the account if a 404 is received 

2. I will create a new function `fundAccount` to handle the account creation process: 

   a. Use the Friendbot service to fund the account on Testnet 

   b. Implement error handling and retries for funding failures 

3. I will update the login flow to incorporate the new account funding logic: 

   a. Attempt to fetch the account as normal 

   b. If a 404 is received, call the `fundAccount` function 

   c. Retry the account fetch after funding 

4. I will add appropriate logging and user feedback for the account creation process. 

5. I will implement a mechanism to distinguish between genuinely new accounts and those affected by Testnet resets. 

6. I will thoroughly test the modified login flow, simulating various scenarios including Testnet resets.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hello @ElliotFriend I am Joseph I am a Software developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. 

### How I plan on tackling this issue

To solve this, I will modify the fetchAccount function in /src/lib/stellar/horizonQueries.js to handle the 404 error. When a 404 response is received from the Horizon server (indicating that the account is no longer live on the Testnet), I will add logic to automatically fund the account. This will involve checking the response for the 404 status and, if detected, triggering the account funding process before retrying the login. This ensures that accounts that were set up before the Testnet reset are automatically funded and can log in successfully. I will complete this in 2-3 days

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I am a blockchain developer with a strong background in html, css, javascript , typescript , this would be my first time contributing to this ecosystem . and i would be glad to work on this issue

### How I plan on tackling this issue
 I will approach this issue by modifying  the fetchAccount function in /src/lib/stellar/horizonQueries.js to detect a 404 error, then automatically fund the account if the account doesn't exist on the Testnet after a reset.
